name: Generate ESI client

on:
  push:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build-openapi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
        always-auth: true
    - uses: actions/checkout@v2
    - name: Generate openapi client
      run: |-
        yarn install
        yarn run generate
        yarn run esi-version
    - name: Commit and push if changed
      id: commit-and-push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        version=$(cat VERSION)
        version_changed=$(git status VERSION --porcelain)
        if [ -n "${version_changed}" ]; then
          yarn version --new-version "${version}.0"
        else
          yarn version --patch
        fi
        git push
        echo "PUBLISH=true" >> $GITHUB_OUTPUT
    - name: Publish if changed
      if: ${{ steps.commit-and-push.outputs.PUBLISH == 'true' }}
      run: |-
        yarn
        yarn run build
        yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.FNTEVE_NPMJS_TOKEN}}